name: push_stuff_for_you

on:
  push:
  pull_request:
    paths:
      - README.md

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: do stuff
        run: |
          echo "# Do something to README.md by github actions ${{ github.sha }}" >> README.md

      - name: Commit and push
        env: 
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          git checkout $BRANCH
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "from ${{ github.sha }}" && git push
